{
 "title": "Endless Loop Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Key Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Events Published And Consumed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_event_count_total",
     "legendFormat": "events"
    },
    { "expr": "kafka_producer_confirmed_total", "legendFormat": "confirmed" },
    {
     "expr": "kafka_producer_unconfirmed_total",
     "legendFormat": "unconfirmed"
    },
    { "expr": "kafka_consumer_count_total", "legendFormat": "consumed" }
   ]
  },
  {
   "title": "Event Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_scheduler_event_count_total[1m])",
     "legendFormat": "rate per min"
    }
   ]
  },
  { "title": "Broker Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Partition Leader",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_admin_partition_leader" }
   ]
  },
  {
   "title": "Partition Replicas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_admin_partition_replicas" }
   ]
  },
  {
   "title": "Topic Retention (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_admin_retention_ms" }
   ]
  },
  { "title": "Producer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Producer Buffer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_buffer_total_bytes",
     "legendFormat": "total"
    },
    {
     "expr": "kafka_producer_buffer_available_bytes",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Producer Avg Batch Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_producer_batch_size_avg" }
   ]
  },
  {
   "title": "Average Production Time (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(kafka_producer_send_timer_seconds_sum[1m]) * 1000) / rate(kafka_producer_send_timer_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Producer Byte Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_producer_byte_rate  " }
   ]
  },
  {
   "title": "Producer Retry Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_record_retry_total  "
    }
   ]
  },
  {
   "title": "Producer Avg Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_request_latency_avg  "
    }
   ]
  },
  {
   "title": "Record Error Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_record_error_total  "
    }
   ]
  },
  { "title": "Consumer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Consumer Group Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_admin_latest_offset) - sum(kafka_admin_consumer_group_offset)"
    }
   ]
  },
  {
   "title": "Assigned Partitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_assigned_partitions_partitions)  "
    }
   ]
  },
  {
   "title": "Rate Of Consumption",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_admin_consumer_group_offset[1m])"
    }
   ]
  },
  {
   "title": "Consumer Group Offset",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_admin_consumer_group_offset"
    }
   ]
  }
 ]
}